config/routes.rb
Gemelitas::Application.routes.draw do
  resources :invitados

  devise_for :admins, :path => "admins", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }


  resources :slides

  devise_for :usuarios, :path => "usuarios", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }


  get "home/index"

  root :to => "home#index"
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/invitado.rb
class Invitado < ActiveRecord::Base
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  validates :slide, :presence => true
  validates_attachment_content_type :slide, :content_type =>  ['image/png', 'image/jpg', 'image/jpeg']
  validates_attachment_size :slide, :less_than => 4.megabytes

  has_attached_file :slide, :styles => {
                                         :slide => {
                                         :geometry => '950x352#',
                                         :quality => 90,
                                         :format => 'jpg'
                                       }
                                      }
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :registerable, :token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :nombre, :email, :password, :password_confirmation, :remember_me

  def password_required?
    super if confirmed?
  end

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @invitado = Invitado.new
    @slides = Slide.order("created_at DESC")
    today = DateTime.now
    babyshower = Date.new(2012, 12, 01)
    time_until =  babyshower - today
    if time_until.to_i == 0
      @dias_para_el_babyshower = "Hoy es"
    else
      days_to_go = time_until.to_i
      @dias_para_el_babyshower = "Faltan solo <b>" + days_to_go.to_s + "</b> días para"
    end
  end

end

app/controllers/invitados_controller.rb
class InvitadosController < InheritedResources::Base
  before_filter :authenticate_admin!, :except => [:create]
  def create
    @invitado = Invitado.new(params[:invitado])
    ContactMailer.contact_confirmation(@invitado).deliver
    ContactMailer.contact_notification(@invitado).deliver
    create!(:notice => 'Confirmadazo, ya estás en la lista de invitados, eres un éxito con esto del internet.') { root_path }
  end
end

app/controllers/slides_controller.rb
class SlidesController < InheritedResources::Base
  before_filter :authenticate_admin!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def resource_name
    :usuario
  end

  def resource
    @resource ||= Usuario.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:usuario]
  end

end

app/helpers/invitados_helper.rb
module InvitadosHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/home/_countdown.html.erb
<script type="text/javascript">
$(function () {
	var austDay = new Date();
	austDay = new Date(austDay.getFullYear(), 12 - 1, 01, 15);
	$('#defaultCountdown').countdown({until: austDay, timezone: -5});
  $('#defaultCountdown').countdown($.countdown.regional['es']);
});
</script>

app/views/home/_facebook.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=236994876375045";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/home/index.html.haml
- page_title! 'Babyshower'

= render 'countdown'
= render 'facebook'

.wrapper
  %h2.main-title
    Faltan:
    %br
    #defaultCountdown
    %br
    para el babyshower de las gemelitas.
  = render 'scripts/royal_slider'
  = render 'scripts/royal_slider_init'
  = render 'slides/lista'

  <iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fgemelitas-sp.org%2F&amp;send=false&amp;layout=standard&amp;width=950&amp;show_faces=true&amp;action=like&amp;colorscheme=dark&amp;font&amp;height=80&amp;appId=236994876375045" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:950px; height:80px;" allowTransparency="true"></iframe>


  %section#confirmar-asistencia.region
    %h3.title
    .confirmar
      %b
        confirmar tu asitencia es fácil
      %br
      llena tu nombre y tu e-mail, presiona enviar
      %br
      = render 'invitados/form'
    .fecha
      sábado 01|12
      %br
      3:00 pm

  %section#que-acontecera.region
    %h3.title ¿Qué acontecerá ese día?
    .informacion
      %p
        Este sábado primero de diciembre están invitados al baby shower de las gemelas. Es mixto, pueden ir chicos y chicas, habrá bocadillos, emparedados de mantequilla de maní con plátano, etc.
      %p
        Estamos preparando un buffet de brochetas de arroz y lentejas rellenas de pavo, ojalá acabemos a tiempo.
      %p
        No se olviden de darle like, compartir la página en su muro de facebook y llevar lindos obsequios para nuestras futuras angelitas.
      %p
        Después del babyshower vamos a usar esta página para postear las fotos de ese día y algunas noticias.
      %p
        Pronto tendremos fantásticas sorpresas.
      %br
      %p
        ¿Estás feliz por el babyshower? Déjanos tus comentarios, los vamos a guardar hasta que las gemelas sepan leer.
      %br
      <div class="fb-comments" data-href="http://gemelitas-sp.org/" data-num-posts="12" data-width="950" data-colorscheme="dark"></div>


  %section#como-llegar.region
    %h3.title ¿Cómo llegar?
    .direccion
      Av. Pardo 399, segundo piso, Miraflores / La Alameda y Hacienda club
    .mapa
      <iframe src="http://www.map-generator.org/65ba14de-0768-4aa1-9f6d-94520e6b5560/iframe-map.aspx" scrolling="no" height="352px" width="950px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>

  %section#lista-del-bebe.region
    %h3.title Lista del bebé Ripley
    .codigo
      código: <b>2764587-9</b>
    %p
      Si vas a Ripley a comprar el regalo para las gemelitas o cualquier cosa que necesitas de la sección bebés, dando nuestro código nos harás acumular puntos y los podremos canjear por lindos obsequios para las gemelitas. ¿Lo máximo no?

  %section#preguntas.region
    %h3.title ¿Preguntas?
    .telefonos
      %ul
        %li Anita Guevara | 994148878, 414*8878
        %li Andrea Pastor | 987098744
    .correo
      hola@gemelitas-sp.org

app/views/invitados/_form.html.haml
= form_for(@invitado, :url => { :controller => 'invitados', :action => 'create' }) do |f|
  -if @invitado.errors.any?
    #error_explanation
      %h2= "#{pluralize(@invitado.errors.count, "error")} prohibited this invitado from being saved:"
      %ul
        - @invitado.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nombre, "nombre"
    = f.text_field :nombre
  .field
    = f.label :email, "e-mail"
    = f.text_field :email
  .actions
    = f.submit 'Enviar'

app/views/invitados/edit.html.haml
%h1 Editing invitado

= render 'form'

= link_to 'Show', @invitado
\|
= link_to 'Back', invitados_path

app/views/invitados/index.html.haml
%h1 Listing invitados

%table
  %tr
    %th Nombre
    %th Email
    %th
    %th
    %th

  - @invitados.each do |invitado|
    %tr
      %td= invitado.nombre
      %td= invitado.email
      %td= link_to 'Show', invitado
      %td= link_to 'Edit', edit_invitado_path(invitado)
      %td= link_to 'Destroy', invitado, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Invitado', new_invitado_path

app/views/invitados/new.html.haml
%h1 New invitado

= render 'form'

= link_to 'Back', invitados_path

app/views/invitados/show.html.haml
%p#notice= notice

%p
  %b Nombre:
  = @invitado.nombre
%p
  %b Email:
  = @invitado.email

= link_to 'Edit', edit_invitado_path(@invitado)
\|
= link_to 'Back', invitados_path

app/views/layouts/_menu.html.haml
%ul.menu
  %li
    = link_to  '¿Preguntas?', 'javascript:$.scrollTo("#preguntas",800);'
  %li
    = link_to  '¿Cómo llegar?', 'javascript:$.scrollTo("#como-llegar",800);'
  %li
    = link_to '¿Qué acontecerá?', 'javascript:$.scrollTo("#que-acontecera",800);'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= page_title
    = stylesheet_link_tag '/stylesheets/screen.css', '/javascripts/jquery.countdown.css'
    = javascript_include_tag :defaults
    = javascript_include_tag '/javascripts/jquery.countdown.min.js', '/javascripts/jquery.countdown-es.js','/javascripts/libs/jquery.scrollTo-1.4.2/jquery.scrollTo-min.js'
    /[if lt IE 9]
      %script{:src => 'http://html5shim.googlecode.com/svn/trunk/html5.js'}
    = yield :scripts
    = csrf_meta_tag
    = favicon_link_tag "/favicon.png"
    == <meta name="keywords" content="" />
    == <meta name="description" content="" />
    == <meta name="googlebot" content="index,follow" />
    == <meta name="robots" content="index,follow" />
    == <meta name="Revisit-After" content="7 days" />
    == <meta name="city" content="Lima" />
    == <meta name="country" content="Peru" />
    == <meta name="state" content="Lima" />
    == <meta name="zip code" content="Lima18" />
    == <meta name="subject" content="" />
    == <meta name="author" content="Kosmyka.com" />
    == <meta name="copyright" content="&copy;Todos los derechos reservados." />
    == <meta name="geo.placename" content="Lima, Peru" />
    == <meta name="geo.region" content="PE-Lima" />
    == <meta name="google-site-verification" content="EsdsLyvLs5l-BaSMnU8k8FFmZbvfC8Gc90IOyKOVJfY" />

  %body
    - if notice
      %p.notice= notice

    %header
      .wrapper
        %h1.site-name
          = link_to 'Gemelitas Sutcliffe Pastor', 'javascript:$.scrollTo("body",800);'

        = render 'layouts/menu'
    %section#content{:role => 'main'}
      = yield

    %footer#footer-bottom.sixteen.columns
      .inner
        %p#social-links
          = link_to 'Link al evento en el facebook', 'http://www.facebook.com/events/330718627035172'
        %p#author
          = link_to image_tag('/images/kosmyka.png'), 'http://www.kosmyka.com', :target => '_blank'
    = render 'shared/google_analytics'

app/views/scripts/_royal_slider.html.haml
- content_for :css do
  = stylesheet_link_tag "/javascripts/libs/royal-slider-9.2/royalslider.css", "/javascripts/libs/royal-slider-9.2/rs-default.css"

- content_for :scripts do
  = javascript_include_tag "/javascripts/libs/royal-slider-9.2/jquery.royalslider.custom.min.js", "/javascripts/libs/royal-slider-9.2/jquery.easing-1.3.js"

app/views/scripts/_royal_slider_init.html.haml
:css
  #preface-top .royalSlider{width:950px; height:352px; margin-bottom:70px; overflow:hidden; background:url(../images/backgrounds/bg-slide-shadow.png) no-repeat 50% 312px; padding-bottom: 50px;}
  .rsOverflow{position:relative}
  .rsABlock{position:absolute; top:5px; /* bottom:auto;*/  left:auto;  right:35px}
  .rsDefault .rsPreloader {background-image:url(/javascripts/libs/royal-slider-9.2/preloaders/preloader-white.gif)}
  .rsDefault .rsCloseVideoIcn {background: url('/javascripts/libs/royal-slider-9.2/rs-default.png') -64px 0}
  .rsSlide {position:absolute; top:0; float:left}


:javascript
  // HOME SLIDER
  jQuery(document).ready(function($) {
    $('.royalSlider').royalSlider({
      autoPlay: {
      // autoplay options go gere
      enabled: true,
      pauseOnHover: true,
      stopAtAction: false
    },
    block: {
    // animated blocks options go gere
      fadeEffect: false,
      moveEffect: 'top',
      delay: 500,
      speed: 150,
      easing:'easeOutSine'
    },
    arrowsNav: true,
    allowCSS3: true,
    arrowsNavAutoHide: true,
    fadeinLoadedSlide: false,
    //controlNavigationSpacing: 0,
    //controlNavigation: 'bullets',
    imageScaleMode: 'none',
    imageAlignCenter:false,
    blockLoop: true,
    loop: true,
    numImagesToPreload: 6,
    transitionType: 'move',
    keyboardNavEnabled: true,
    sliderDrag: true,
    sliderTouch: true,
    keyboardNavEnabled: true,
    });

  });  // END OF DOCUMENT READY

app/views/shared/_google_analytics.html.erb
<script type="text/javascript" charset="utf-8">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36446272-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/slides/_form.html.haml
= form_for @slide, :html => { :multipart => true } do |f|
  -if @slide.errors.any?
    #error_explanation
      %h2= "#{pluralize(@slide.errors.count, "error")} prohibited this slide from being saved:"
      %ul
        - @slide.errors.full_messages.each do |msg|
          %li= msg


  .field
    = f.label :slide
    = f.file_field :slide
  .actions
    = f.submit 'Guardar'

app/views/slides/_lista.html.haml
#preface-top
  .royalSlider.rsDefault
    - @slides.each do |slide|
      %div
        = image_tag slide.slide(:slide), :class => 'rsImg'
        -if current_admin
          %td= link_to 'Ver', slide
          %td= link_to 'Editar', edit_slide_path(slide)
          %td= link_to 'Eliminar', slide, :confirm => 'Are you sure?', :method => :delete

app/views/slides/edit.html.haml
%h1 Editing slide

= render 'form'

= link_to 'Show', @slide
\|
= link_to 'Back', slides_path

app/views/slides/index.html.haml
%h1 Listing slides

=render 'lista'

%br

= link_to 'Nuevo Slide', new_slide_path

app/views/slides/new.html.haml
%h1 New slide

= render 'form'

= link_to 'Back', slides_path

app/views/slides/show.html.haml
%p#notice= notice

= image_tag @slide.slide(:slide)


= link_to 'Edit', edit_slide_path(@slide)
\|
= link_to 'Back', slides_path